name: Push Code to Frontend and Backend Branch
on:
  push:
    paths:
      - frontend/**
      - backend/**

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Deploy Frontend Code
        if: github.event.head_commit.message != 'skip frontend'
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: frontend
          FOLDER: frontend
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
    
      - name: Deploy Backend Code
        if: github.event.head_commit.message != 'skip backend'
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: backend
          FOLDER: backend
          GITHUB_TOKEN: ${{ secrets.TOKEN }}